import 'package:onlyveyou/models/product_model.dart';

final List<ProductModel> dummyProducts = [
  ProductModel(
    productId: '1',
    name: '[바이오힐보] 프로바이오더마 3D 리프팅 크림 앰플 기획세트 50ml + 앰플 증정',
    brandName: '바이오힐보',
    productImageList: ['assets/image/skin2.webp'],
    descriptionImageList: [],
    price: '35000',
    discountPercent: 22,
    stock: 100,
    categoryId: '1',
    favoriteList: ['temp_user_id'],
    reviewList: List.generate(1234, (index) => 'review_$index'),
    tagList: ['BEST'],
    isBest: false,
    rating: 4.8,
  ),
  ProductModel(
    productId: '2',
    name: '[단델리온] 엑스트라 골드 페이셜 트리트먼트 오일 100ml 대용량 기획',
    brandName: '단델리온',
    productImageList: ['assets/image/skin3.webp'],
    descriptionImageList: [],
    price: '28000',
    discountPercent: 12,
    stock: 100,
    categoryId: '1',
    favoriteList: [],
    reviewList: List.generate(2156, (index) => 'review_$index'),
    tagList: [],
    isBest: false,
    rating: 4.9,
  ),
  ProductModel(
    productId: '3',
    name: '[수디] 프리미엄 저자극 토너&세럼 기초 2종 세트 500ml + 미니어처 증정',
    brandName: '수디',
    productImageList: ['assets/image/skin4.webp'],
    descriptionImageList: [],
    price: '25000',
    discountPercent: 21,
    stock: 100,
    categoryId: '1',
    favoriteList: ['temp_user_id'],
    reviewList: List.generate(892, (index) => 'review_$index'),
    tagList: [],
    isBest: false,
    rating: 4.7,
  ),
  ProductModel(
    productId: '4',
    name: '[포맨트] 시그니처 퍼퓸 50ml 오리지널 블랙 에디션 + 샘플러 키트',
    brandName: '포맨트',
    productImageList: ['assets/image/skin5.jpg'],
    descriptionImageList: [],
    price: '16000',
    discountPercent: 20,
    stock: 100,
    categoryId: '2',
    favoriteList: [],
    reviewList: List.generate(456, (index) => 'review_$index'),
    tagList: [],
    isBest: false,
    rating: 4.5,
  ),
  ProductModel(
    productId: '5',
    name: '[아르테] 블랙라벨 옴므 스킨케어 5종 세트 + 쉐이빙 젤 증정 한정판',
    brandName: '아르테',
    productImageList: ['assets/image/skin6.jfif'],
    descriptionImageList: [],
    price: '42000',
    discountPercent: 19,
    stock: 100,
    categoryId: '2',
    favoriteList: ['temp_user_id'],
    reviewList: List.generate(3102, (index) => 'review_$index'),
    tagList: ['BEST'],
    isBest: true,
    rating: 4.9,
  ),
  ProductModel(
    productId: '6',
    name: '[달바] 화이트 트러플 퍼스트 스프레이 세럼 더블 이펙트 미스트 100ml',
    brandName: '달바',
    productImageList: ['assets/image/skin7.jfif'],
    descriptionImageList: [],
    price: '31000',
    discountPercent: 18,
    stock: 100,
    categoryId: '1',
    favoriteList: ['temp_user_id'],
    reviewList: List.generate(1567, (index) => 'review_$index'),
    tagList: [],
    isBest: false,
    rating: 4.6,
  ),
  ProductModel(
    productId: '7',
    name: '[단델리온] 프리미엄 골드 에센스 페이셜 오일 150ml 대용량 리미티드',
    brandName: '단델리온',
    productImageList: ['assets/image/skin8.jfif'],
    descriptionImageList: [],
    price: '45000',
    discountPercent: 18,
    stock: 100,
    categoryId: '1',
    favoriteList: [],
    reviewList: List.generate(2789, (index) => 'review_$index'),
    tagList: ['BEST'],
    isBest: true,
    rating: 4.8,
  ),
  ProductModel(
    productId: '8',
    name: '[수디] 프로바이오틱스 진정 수분 크림 & 토너 듀오 세트 특별 기획',
    brandName: '수디',
    productImageList: ['assets/image/skin9.jfif'],
    descriptionImageList: [],
    price: '39000',
    discountPercent: 19,
    stock: 100,
    categoryId: '1',
    favoriteList: ['temp_user_id'],
    reviewList: List.generate(1893, (index) => 'review_$index'),
    tagList: [],
    isBest: false,
    rating: 4.7,
  ),
  ProductModel(
    productId: '9',
    name: '[포맨트] 시그니처 퍼퓸 컬렉션 75ml 스페셜 에디션 + 미니어처 세트',
    brandName: '포맨트',
    productImageList: ['assets/image/skin10.jfif'],
    descriptionImageList: [],
    price: '28000',
    discountPercent: 20,
    stock: 100,
    categoryId: '2',
    favoriteList: [],
    reviewList: List.generate(2341, (index) => 'review_$index'),
    tagList: ['BEST'],
    isBest: true,
    rating: 4.9,
  ),
  ProductModel(
    productId: '10',
    name: '[아르테] 프리미엄 블랙 에센셜 올인원 플루이드 200ml + 클렌저 증정',
    brandName: '아르테',
    productImageList: ['assets/image/skin2.webp'],
    descriptionImageList: [],
    price: '32000',
    discountPercent: 20,
    stock: 100,
    categoryId: '2',
    favoriteList: ['temp_user_id'],
    reviewList: List.generate(1987, (index) => 'review_$index'),
    tagList: ['BEST'],
    isBest: true,
    rating: 4.8,
  ),
];
